hardware_mapping: "regular"
rows: 32
cols: 32
chain_length: 1
parallel: 1
pwm_bits: 11
pwm_lsb_nanoseconds: 130
pwm_dither_bits: 0
brightness: 100
scan_mode: 0
row_address_type: 0
multiplexing: 0
disable_hardware_pulsing: False
show_refresh_rate: False
inverse_colors: False
led_rgb_sequence: "RGB"
pixel_mapper_config: ""
panel_type: ""
limit_refresh_rate_hz: 0
gpio_slowdown: 1
daemon: 0
drop_privileges: 1
do_gpio_init: True
imu_dev: "/dev/i2c-0"
imu_address: 0x68